### PR TITLE
Add open console links in chrome profile functions

### PR DESCRIPTION
**Pull request by GeoffBarnettSTHLM**
This branch provides integration with the chrome browser, two new shell commands are provided:

open_console_session - Creates a Console URL with a session token for the assumed role and opens the AWS console in the chrome browser.  The link is opened in chrome using a chrome user profile with the name of the assumed role, the first link that uses this assumed role opens a new browser window, subsequent URL's opened with the same assumed role will be opened as tabs in the same browser window.

open_console_link - Creates a link to a specific location within the AWS console, this could be a service page or individual resource.  The link is opened in chrome using a chrome user profile with the name of the assumed role, the first link that uses this assumed role opens a new browser window, subsequent URL's opened with the same assumed role will be opened as tabs in the same browser window.

Use of a profile for each role, allows the user to have multiple concurrent AWS console sessions, using different accounts or different roles, at the same time, using the same browser, without needing to copy and paste URL's from the CLI in to separate incognito windows.   This also allows programmatic calling of AWS console windows using a default browser, without needing to log out of existing sessions that are using different accounts or roles.

### CODE REVIEW

**Comment by stonefield** [comment]
I think this could be made much DRYer. The `open_console_session` could just take an url optionally, and `open_console_link` could just be eliminated

**Comment by GeoffBarnettSTHLM** [comment]
I'm sure it could be DRYer, but there wasn't very good documentation in the code about what everything is doing and this was a quick hack.  I tried to have the open_console_link command just take a URL, but I couldn't get it to work.

**Comment by arnvid** [comment]
I would really like there to be a command for each....  These are two very different use cases -

**Comment by bjornrog** [comment]
Comment to the request by Arnvid about the new functionality to be separate commands. That would duplicate some code. I can see good reasons for both (separate command and options), but with this approach you can just ignore the added options and make your aliases as you like. Meaning we can support both  use cases.

**Pull request merged**
